name: Dump context
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: sw2m/octoscript/action@main
      - id: prod
        run: await output.set("val", "hello");
        shell: octoscript {0}
      - run: console.log(JSON.stringify(context, null, 2));
        shell: octoscript {0}
